project:
  type: book
  output-dir: _book

book:
  title: "OpenCollections Manual"
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
     - name: "Ádám Lázár"
       orcid: 0009-0000-7257-3690
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/ 
     - name: "Andor Kornél Barát"
       orcid: 0009-0005-6773-6543
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
     - name: "Anna Márta Mester"
       orcid: 0009-0008-2274-8163
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
  date: today
  repo-url: https://github.com/dataobservatory-eu/opencollections-manual
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - glossary.qmd
    - inspiration.qmd
    - tidy.qmd
    - collections.qmd
    - wikidata.qmd
    - wikibase.qmd
    - sandbox.qmd
    - bulk-import.qmd
    - opencollections.qmd
    - references.qmd
  appendices:
    - questionbank.qmd
    - musicapi.qmd
    - iscc.qmd

version: 0.2.33
doi: 10.5281/zenodo.13912121

bibliography: 
    - bib/cm.bib
    - bib/collections.bib
    - bib/datamodels.bib
    - bib/ddi.bib
    - bib/identifiers.bib
    - bib/ISOdata.bib
    - bib/metadata.bib
    - bib/musicidentifiers.bib
    - bib/nerd.bib
    - bib/wikidata.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default 
  docx: default

editor: visual

